version = 1
name = "creators-mobile"

[setup]
script = ""

[[actions]]
name = "Run"
icon = "run"
command = "./script/build_and_run.sh"

[[actions]]
name = "Run Web"
icon = "run"
command = "./script/build_and_run.sh --web"
